### ISSUE TITLE
Ability to copy TOTP quickly in right-click context menu

### ISSUE THREAD

**Issue by scruel** [Rookiestyle/KeePassOTP#116]
![image](https://user-images.githubusercontent.com/16933298/203261591-40552af7-4f56-446d-aba4-9cd19fb09430.png)

**Comment by Rookiestyle** [comment]
There are already many ways to copy the TOTP.

1. Doubleclick the KPOTP column - Yan can decide to show ***** instead of the actual TOTP. Copying is still possible
2. Show the conext menu -> KeePassOTP -> Copy OTP
3. Use the KPOTP hotkey. You can define it in the plugin options. Inside KeePass it will copy the OTP of the selected entry, outside KeePass it will auto-type it if you want

I don't plan to add another option for that
