### ISSUE TITLE
How to delete saved TOTP record?

### ISSUE THREAD

**Issue by scruel** [Rookiestyle/KeePassOTP#117]
![image](https://user-images.githubusercontent.com/16933298/203262158-3cd32d1b-1af2-43c3-b279-27fd552fe6ad.png)

Since I can't directly open sub-database, and delete fields for record in main database won't take any effects, I can still see them in right-click context menu with tray icon.

**Comment by Rookiestyle** [comment]
I can't reproduce this.
After I delete an entry, it does not show up in the tray.

I attached a test database. It contains two entries, both have TOTP set up.
Entry 1 is in the database root group.
Entry 2 is deleted and currently located in the recycle bin.
The tray only shows Entry 1.
Entry 2 is only shown when I move it out of the recycle bin.

If I directly delete Entry 2, the result is the same.

What happens if you open the database?
password for database: test
passwword for included OTP database: testtest
[deleted_totp.zip](https://github.com/Rookiestyle/KeePassOTP/files/10069552/deleted_totp.zip)




Can you provide a test database for me to analyze?

**Comment by scruel** [comment]
> I can't reproduce this. After I delete an entry, it does not show up in the tray.
> 
> I attached a test database. It contains two entries, both have TOTP set up. Entry 1 is in the database root group. Entry 2 is deleted and currently located in the recycle bin. The tray only shows Entry 1. Entry 2 is only shown when I move it out of the recycle bin.
> 
> If I directly delete Entry 2, the result is the same.
> 
> What happens if you open the database? password for database: test passwword for included OTP database: testtest [deleted_totp.zip](https://github.com/Rookiestyle/KeePassOTP/files/10069552/deleted_totp.zip)
> 
> Can you provide a test database for me to analyze?

Sorry, description may cause misunderstanding, it's not about delete the entry, it's about how to remove TOTP from an entry without deleting it.

**Comment by Rookiestyle** [comment]
OK, understood.

I will add a "Delete" option in the next release
In the meantime: Open KeePassOTP setup for that entry, clear the Seed field and save.
This will delete TOTP from your entry.
