### ISSUE TITLE
Ignore empty otp fields

### ISSUE THREAD

**Issue by drellmark** [Rookiestyle/KeePassOTP#123]
I am using Entry Templates for KeePass and created a account template with an 2FA URI field (named otp, so KeePassOTP can use it).
Entry Templates for KeePass always automatically add an empty otp field if I create a new account (KeePass entry) using this template. This is true even if I currently do not enter a 2FA URI in the otp field.
In the KPOTP column of the KeePass main window this new account (KeePass entry) then shows "ERROR" as content.
It would be nice if KeePassOTP would handle such entries like if the otp field does not exist and would show "Setup 2FA" and would not show them in the tray menu of KeePass.

Using two different templates for accounts with and without a 2FA option is cumbersome and unpractical. First, the template without 2FA must be removed from the account, then the entry must be closed (saved), then reopened again and assigned the account template with 2FA options and finally I would be able to add the new otpauth URI and save the entry again. Not to say that I have to manage two identical templates which only differs in the additional otp field.

Using: KeePass 2.53, KeyPassOTP 1.6.3, Entry Templates for KeePass 8.0.0.0

**Comment by Rookiestyle** [comment]
If you use KeePassOTP, why do you include an empty OTP field in your template? There is no need to do so.

KeePassOTP will show "Setup 2FA" if 2FA can be set up even if the field does not exist. It will also create the field when you actually set up 2FA.

An empty OTP is invalid and KeePassOTP cannot tell whether it's empty because of the template or because of different reasons.

**Comment by Rookiestyle** [comment]
Close due to no feedback
