### ISSUE TITLE
Copy OTP does not copy the OTP

### ISSUE THREAD

**Issue by theking2** [Rookiestyle/KeePassOTP#146]
## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Setup in KeePassOTP/OTP Setup
2. Select an entry and clock other data/Copy OTP
3. 

## Expected Behavior
THe current OTP is copied to the clipboard

## Actual Behavior
A string like this is copied
`otpauth://totp/blob:blub?secret=XXXXXXXXXXXXX&issuer=blob`

## Context
[NOTE]: # (Provide any additional information you may have)
OS: 
KeePass Version:2.55
Plugin Version:1.6.7

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
other data -> otp is wrong
Doing so will copy the entire [otpauth](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) url instead of the generated OTP value
This otpauth string is required to calculate the OTP value

These are the options to copy the OTP values 
* Rightclick -> KeePassOTP -> Copy OTP (you can also assign a hotkey for that in KeePassOTP's options)
* Menu: Entry ->  KeePassOTP -> Copy OTP
* Doublick value in column KPOTP
