### ISSUE TITLE
Mobile support for KeePassOTP

### ISSUE THREAD

**Issue by UsefulVid** [Rookiestyle/KeePassOTP#16]
The "old" plugins like KeeOTP were compatible with keepass2android app and I could generate OTP codes from the app.
This seems to be broken now.
Therefore I opened up 2 issues for KeePassDX App and keepass2android:

https://github.com/Kunzisoft/KeePassDX/issues/689 --> looks like this already works
https://github.com/PhilippC/keepass2android/issues/1401

Hope they integrate your format soon

**Comment by Rookiestyle** [comment]
Hi, if you configure KeePassOTP to NOT use a separate db for otp secrets (have a look at the options) KeePass2Android should work.Am 07.09.20, 08:42 schrieb UsefulVid <notifications@github.com>:

   
  The "old" plugins like KeeOTP were compatible with keepass2android app and I could generate OTP codes from the app. This seems to be broken now. Therefore I opened up 2 issues for KeePassDX App and keepass2android: 
  Kunzisoft/KeePassDX#689 PhilippC/keepass2android#1401 
  Hope they integrate your format soon

**Comment by UsefulVid** [comment]
> Hi, if you configure KeePassOTP to NOT use a separate db for otp secrets (have a look at the options) KeePass2Android should work.

Nope. I do not use a separate DB and it does not work

**Comment by Rookiestyle** [comment]
That's weird. In one of my databases I have to trace of stored in the field called top and it has the Kuwaiti value string and it works.Let's wait for the KeePass2Android author to checkAm 07.09.20, 10:23 schrieb UsefulVid <notifications@github.com>:

   
   
   Hi, if you configure KeePassOTP to NOT use a separate db for otp secrets (have a look at the options) KeePass2Android should work. 
   
  Nope. I do not use a separate DB and it does not work

**Comment by Rookiestyle** [comment]
KeePassOTP supports two different approaches for the otp-secret: [Details](https://github.com/Rookiestyle/KeePassOTP/wiki/KeePassOTP-storage-approaches)

For one of my databases where I store the secret in the format mentioned above, I don't experience this issue.
Only difference: I'm using `otpauth://totp/<label>?secret=xxxxxxxxxxxxxx&issuer=KeePassOTP`instead of `otpauth://totp?secret=xxxxxxxxxxxxxx&issuer=KeePassOTP`

According to https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label the label is optional and may consists of either account name or issuer & account name and all variants seem to be supported by KeePass2Android as well.

Can you try with adding a slash between totp and ?

**Comment by UsefulVid** [comment]
Adding the slash worked fine. It can now generate totp codes
