### ISSUE TITLE
Wiki: document how to use KeePassOTP with Steam OTP/2FA

### ISSUE THREAD

**Issue by koitsu** [Rookiestyle/KeePassOTP#21]
I've written documentation explaining how to use KeePassOTP with Steam (for OTP/2FA):

https://github.com/koitsu/KeePassOTP/wiki/Using-KeePassOTP-with-Steam

Sadly GitHub [does not provide a way to do PRs for Wiki pages](https://stackoverflow.com/a/11481887), but you have my permission to take the raw Markdown document from https://github.com/koitsu/KeePassOTP.wiki.git and use it, including modifying it however you wish.

Hope this helps, and thank you for KeePassOTP!

**Comment by Rookiestyle** [comment]
Many thanks for providing these instructions, this indeed is helpful!

I released them in a slightly modified version, main change: I added a *Note* on my own, explaining to **not** define an encryption key as I was unable to read the maFiles otherwise.

Just let me know in case I should change something.

**Comment by koitsu** [comment]
Ah yes, I forgot that part of the process.  I left the field empty (no encryption key) for that very reason.  Thanks!  You can incorporate this + close when you see it fit.

**Comment by Rookiestyle** [comment]
Done, thanks

https://github.com/Rookiestyle/KeePassOTP/wiki/Using-KeePassOTP-with-Steam
