### ISSUE TITLE
KeePassOTP and Yandex account

### ISSUE THREAD

**Issue by barney09** [Rookiestyle/KeePassOTP#25]
Hello. KeePass OTP and Yandex.Key don`t work together. But maybe there is a solution.

Somebody already created 2FA plugin for Yandex.Key:
https://github.com/norblik/KeeYaOtp

I don't know if it's safe to trust this plugin.
Can you check?

If the code is safe, can you use code from KeeYaOtp plugin and add this code to KeePassOTP?

**Comment by Rookiestyle** [comment]
I personally would make more use of [ProtectedStrings](https://keepass.info/%0D/help/base/security.html#secmemprot) instead of unencrypted strings when calculating the Yandex OTP but that's my opinion only.

My main issue is: I can't get the plugin to work for me
I installed the plugin, created a Yandex account and the QR can be decoded to something like that: `otpauth://yaotp/dummyuser?SECRET=PSO3IEHCZKPNES2TDAEAZEUYDI&name=dummyuser&trackid=somestring&uid=someotherstring&pin_length`

Displaying the secret key instead of the QR code also shows `PSO3IEHCZKPNES2TDAEAZEUYDI`

If I now enter this secret key i to the setup form, it's not accepted by the plugin. Also trackid and uid are not accepted.

Does it work for you aand if yes, what exactly do you enter?

If there is a description of the algorithm available and I'm able to test it, I'll reconsider adding Yandex OTP. Please simply reopen this issue in that case.

For now I won't add it, simply as I can't implement an unknown algorithm that I cannot even test.
