### ISSUE TITLE
Since 0.24 when using Kee for autofill the {KPOTP} is not replaced

### ISSUE THREAD

**Issue by tarzanek** [Rookiestyle/KeePassOTP#46]
Hello
thanks for great plugin!
I use it with latest Keepass, Firefox and Kee plugin for autofill
However last releases borked Kee a bit ...
Last working version was 0.23 (so I stick to it for now)

From 0.24 what used to work with Kee, now just fills {KPOTP} instead of time OTP 

if I replace it with {TimeOTP} it gets filled, but with wrong entry (last time I tried with 0.25, didn't test 0.25.1 with this approach, I saw you did some changes in counting, but not sure related to which fields)

From my POV this is a regression, however if KPOTP shouldn't be used anymore as field for fill in with Kee, I'll gladly fix my entries

Can you let me know what is supposed to work and what doesn't now?

tia
L

**Comment by Rookiestyle** [comment]
I'm not that familiar with Kee.
Do you have Kee configured to use {KPOTP} directly or do you configure Kee to fill in a specific string field and this string field has the value {KPOTP}

Did you do anything else beside updating KeePassOTP?
Can you create an example database and attach it here for me to check?

I'm mainly confused because I understand that {KPOTP} is printed "as-is", it should either be replaced by the current OTP or by an error message in case {KPOTP} is an unknown placeholder

**Comment by tarzanek** [comment]
I only updated KeePassOTP

Kee is here: https://github.com/kee-org/browser-addon  (for firefox it is on mozilla store)
how do you fill in passwords in firefox?

Where would I be able to see this error message you mentioned? I can check and ev. send you a patch if I see what exactly failed.

**Comment by tarzanek** [comment]
Autofill of TOTP using Kee is here: https://forum.kee.pm/t/placeholder-handling/1100
and they suggested KPOTP should be used before, fwiw TOTP doesn't work too in 0.24+ and just fails to be replaced

and thnx for looking into this @Rookiestyle

**Comment by Rookiestyle** [comment]
Version 0.25.2 does contain the required fix

**Comment by tarzanek** [comment]
<3 thanks, confirmed & up and running now! :-)

**Comment by dgdedomingo** [comment]
Hello
I'm bringing this message back — I'm having the same problem with the latest available versions. Is it an issue on my side, or is it happening to anyone else?
Thanks, best
