### ISSUE TITLE
Doesn't work with Yandex.Key?

### ISSUE THREAD

**Issue by Darthagnon** [Rookiestyle/KeePassOTP#5]
KeePass OTP doesnlt seem to work as a replacement for Yandex.Key - I tried to enable 2FA for my Yandex account in it, but it didn't work.

**Comment by Rookiestyle** [comment]
I was not able to find more Information while checking https://yandex.com/support/passport/authorization/twofa.html

Based on the developers' feedback on Google Playstore, Yandex uses a proprietary algorithm to generate the 2FA Codes for Yandex.
As this is non-standard and the implementation details are not available, I'm afraid nothing can be done here.
If these details are published in future, I might consider adding it as a new feature.

> Codes for Yandex are non-numeric which means one is forced to use their app rather than one's own preferred authenticator app. ...
**Yandex AppsMay 16, 2020**
**Andreas, we are using our own 2FA standard**, but also support open standards, so you can use our app instead of other authenticators. 

Source: https://play.google.com/store/apps/details?id=ru.yandex.key&hl=en_US&reviewId=gp%3AAOqpTOHN4CLuAGIyX6uATjMYXlCrApoXW7SHoxvSpTLl0t4-0IPnlENTlB_xxEWJASGGCuoiu1igYB0jhzXX44k

You should be able to use KeePassOTP for all other accounts though


Side-note: The standard totp/hotp algorithm has been assessed from security point of view, Yandex' own implementation has not been assessed - at least that's my assumption as this would require sharing the implementation details for generating the 2FA codes.
I personally always dislike the security of one of my accounts depending on this kind of obscurity.
Not saying it is not secure, one simply does not know...

**Comment by barney09** [comment]
Somebody created KeeYaOtp plugin for Yandex.Key:
https://github.com/norblik/KeeYaOtp
Can you use code from KeeYaOtp and add it to KeePassOTP?

**Comment by badigit** [comment]
> Somebody created KeeYaOtp plugin for Yandex.Key:
> https://github.com/norblik/KeeYaOtp
> Can you use code from KeeYaOtp and add it to KeePassOTP?

it will be nice. Reopen issue?

**Comment by Rookiestyle** [comment]
I was already working on this in the last week's and will publish a new release soon.

**Comment by nikicat** [comment]
Hey @Rookiestyle do you have any updates on this issue?
