### ISSUE TITLE
How do I clean a database from KeePassOTB database?

### ISSUE THREAD

**Issue by canerguclu** [Rookiestyle/KeePassOTP#6]
## Summary
I am an end user for this plugin.
As far as I realized, even if you use "separate database" once, the database file creates a OTP database for OTP seeds, burried in the "master" database file. Even if I switch to not using a separate database, then back to using separate database, there's always some garbage coming back from this OTP database, I thought were gone.
How do I clean up my database from this?

**Comment by Rookiestyle** [comment]
In order to not lose any data, the KeePassOTP database is not deleted when switching to entry-specific storage - users might forget to migrate their otp data...
If you want to delete the KeePassOTP database, you currently have to delete it manually.

1. Tools -> Database Tools -> Database Maintenance...
2. Switch to tab *Plugin Data*
3. Find *KeePassOTP.DB* - This field holds the KeePassOTP database as described in the [wiki](https://github.com/Rookiestyle/KeePassOTP/wiki/KeePassOTP-storage-approaches#otp-storage-in-a-separate-database)
4. Delete

I'll leave this issue open and create a pull request to prompt for deletion of KeePassOTP database if the user decides to switch to entry-specific storage

**Comment by Rookiestyle** [comment]
#9 will add this
