### ISSUE TITLE
A way to integrate into trigger system to prevent syncing when OTP database is not locked

### ISSUE THREAD

**Issue by canerguclu** [Rookiestyle/KeePassOTP#7]
I am synchronizing my database file with another file in my onedrive folder using the trigger system, this way I get to have it also on my phone.
As I understand in wiki, if the OTP database is locked this causes data loss. I tested it and realized, even when controlling when syncing happens, I managed to lose data easily. So the warning was very apt.

However, it is of utmost importance that OTP database gets unlocked only as needed (therefore, we have real 2FA). I am torn between syncing to cloud and having OTP database locked, i.e. having convenience of database access on other devices vs having OTA+password available simultaneously in case of a compromise of my database pw. 

If a feature is not feasible, any entry to wiki to solve this issue graciously would be welcome.
Thank you very much.

**Comment by Rookiestyle** [comment]
I'm not sure whether I got it right.
Did you experience data loss eben when the OTP database was unlocked?
Are you concerned of having the OTP database unlocked after a sync happened?
Both?

I can think of locking the OTP database after sync is complete / after a specific timeout (x minutes after last OTP usage)
If there was data loss I need more input: Triggers and - if possible - example databases to reproduce the issue

**Comment by canerguclu** [comment]
I have triggers set at saved database, open database, and periodic (every 10min).

KeePassOTP database was set to auto open when main database was opened, OTP secrets database was separate.

I experienced data lost - lots of ????'s in KPOTP columns. Since I was trying to transition to KeePassOTP, I had my google authenticator as back up for some time.
I am not sure what happened, I am suspecting a wrong OTP database password entry at opening of database causedthis., Because I am not sure at what point does my event trigger kicks in.

Additional info, I am opening this database using KeePassDX app on android. 
As a feature request, I am expecting your suggestion on how to keep OTP locked unless needed and keep main database sync working without data loss.

**Comment by Rookiestyle** [comment]
OK, I installed KeePassDX on my smartphone and I'm not able to reproduce this unfortunately beside changing the same data on both nevices simultaneously as KeePassDX can*t do that according to their wiki

I'ld need the following:
* Your triggers (Export and attach here, please replace sensitive data by placeholders)
* **detailled** steps, example
  * Add OTP for entry A on PC
  * Save on PC
  * Open db on smartphone
  * Change entry A on smartphone
  * Save on smartphone
  * Wait for sync on PC
  * OTP gone...


The OTP database remains locked until needed (if you don't have it auto-open).
It needs to be unlocked to be able to be synched.
Autolocking after sync won't help in your case most likely, as something in the combination of KeePassOTP, triggers and KeePassDX doesn't work as expected.
I don't sync using triggers but by using Google Drive Sync instead and I use KeePass2Android on my Smartphone. That's why I need above mentioned information.

Providing a wrong password for OTP database will result in showing the password prompt again (3 times in total) - unless you changed this KeePass setting.

**Comment by canerguclu** [comment]
Thanks for details answers, I am not a SW engineer even tho I spend significant amount of time scripting for my job. I am tech-savy but no product level software person at all so I appreciate the hand-holding here.

I will try to to replicate and note down a recipe asap. 

The reason I was syncing with triggers was (a) KeePass website suggested this -specifically a dropbox example, (b) somehow my OneDrive kept crashing when I was working the database directly from OneDrive folder, (c) I was not sure what would happen if the database was opened simultaneously on phone and PC (usually a conflicted file scenario ensued in non-keepass scenarios in my experience)

I can definitely switch to Google Drive if the problems above are avoidable.
Regards

**Comment by Rookiestyle** [comment]
I meanwhile released version 0.13.
The OTP database will be backed up as attachment of a newly created entry in the main database if synchronization failes e.g. due to an incorrect masterkey.

This issue will be closed now.
If you're still facing the issue with the new version, please add a step-by-step instruction and I will reopen it.
