### ISSUE TITLE
Configurable hotkey to copy selected entry.

### ISSUE THREAD

**Issue by tom-HCgY7HY6kq** [Rookiestyle/KeePassOTP#80]
In addition to the existing global hotkey to auto-type a matching entry, please can we have a configurable hotkey for within the Keepass window to copy the OTP for the selected entry?

Global hotkeys don't appeal to everyone so having a Keepass only hotkey to copy the entry would provide some extra configuration and make this an even more useful plugin!

**Comment by Rookiestyle** [comment]
You can already use the entry's context menu, doubleclick the KPOTP cell value or use the tray.

What's the benefit of having another KeePass internal hotkey in addition to the global one plus the options mentioned above?

**Comment by tom-HCgY7HY6kq** [comment]
The entry's context menu, doubleclicking the KPOTP cell value or using the tray all require moving your hands from the keyboard to the mouse and so are not quick actions for when you are entering KPOTPs repeatedly/regularly.

I use a lot of web apps and tools which don't tend to work that nicely with the default autotype, so instead of manually configuring lots of custom autotype matches and sequences the most reliable workflow is to use Ctrl-Alt-K to open Keepass, Ctrl-F to find the entry, then use Ctrl-B for the username and Ctrl-C for the password of a selected entry. Something like Ctrl-X would be perfect to add to this workflow for the KPOTP, but with the current global hotkey setup that overrides the native hotkey to Cut and Paste.

I don't think it needs to be an extra hotkey actually. Perhaps just making it configurable whether the existing KPOTP hotkey is global or Keepass local would be enough? Maybe just adding a checkbox in the options to let the user decide whether they would like the hotkey to be global or not?

**Comment by Rookiestyle** [comment]
I'll think about the option to have the existing hotkey work inside KeePass only but this will make the options page even more *crowded*

As a side-note: Ctrl-X is not a good choice imo, it will conflict with e. g. the quick search textbox.

Off-topic: If you logon that regularly, wouldn't it be better to **once** setup a working autotype sequence and press one hotkey instead of 8 (opn KeePass, search, copy username, paste username, copy password, paste password, copy OTP, paste password)?
