### ISSUE TITLE
Import From Google Authenticator

### ISSUE THREAD

**Issue by Minzilein2003** [Rookiestyle/KeePassOTP#90]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Export QR-Code from Google Authenticator
2. Scan QR-Code
3. Insert uri in Text-Field

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)
Load OTP Codes

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)
Following Error:
Expected amount of OTP entries: 1
Found amount of OTP entries: 4

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows
KeePass Version: 2.50 (64-Bit)
Plugin Version: 1.2

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)
![2022-02-04 15_53_26-Database kdbx_ - KeePass](https://user-images.githubusercontent.com/66284145/152550056-db25c592-874d-4fdc-9bae-1dbc2808172c.png)

**Comment by Rookiestyle** [comment]
What happens if you try this uri?
otpauth-migration://offline?data=CkMKFD3GyqSCSm0oh2eyMx4gtDFmy4XZEhxBQ01FIENvOmpvaG4uZG9lQGV4YW1wbGUuY29tGgdBQ01FIENvIAEoATACCjUKCkhlbGxvId6tvu8SGEV4YW1wbGU6YWxpY2VAZ29vZ2xlLmNvbRoHRXhhbXBsZSABKAEwAhABGAEgACjn4Pv4Ag%3D%3D

https://github.com/Rookiestyle/KeePassOTP/wiki/Import-from-Google-Authenticator#3---add-data-to-keepassotp


I can release a version that produces more verbose output and need your support to narrrow the issue down.
Only other option would be to send me your uri string which obviously is not an option... unluss you can create fake accounts in your Google Authenticator and reproduce the issue?

**Comment by Minzilein2003** [comment]
The Uri of you he recognizes and he gives me a selection of codes. I am happy to help fix the problem. I don't like to give out my codes.

**Comment by Rookiestyle** [comment]
I'm not interested in your codes but I was wondering whether you can add a few fake accounts to your Google Authenticator, export those and reproduce the issue by doing so.
If so, please post this uri.
In the meantime let me figure out how to get the uri when exporting on my andoid. Taking a screenshot is not possible and I don't have a 2nd smartphone available right now


With your uri, the selection form is not even displayed, right?

**Comment by Minzilein2003** [comment]
I can create a test QR code for you with uri. 
That is correct. The selection is not displayed to me.

**Comment by Rookiestyle** [comment]
That'll be helpful

**Comment by Minzilein2003** [comment]
I have now got the codes migrated. The problem was that it did not recognize some codes.
For example, it gave me an error with the Twitch code. (Code invalid) When I did all individually, I was able to filter out the error.

**Comment by Rookiestyle** [comment]
I'm able to reproduce this and will release a fixed version soon.
